### ISSUE TITLE
Issue with Facebook Authenctication using nodeJs server & Python server

### ISSUE THREAD

**Issue by naga2raja** [sahat/satellizer#361]
I was been digging up with satellizer for a couple of days. I am a newbie to both AngularJS & nodeJS.

> When I tried to login with Facebook, I am getting the following error in the server (server is nodeJs)

*/var/www/sat/examples/server/node/server.js:466
    if (response.statusCode !== 200) {
                ^
TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/var/www/sat/examples/server/node/server.js:466:17)*

> When I try changing the server with Python, I m getting the following error:

*127.0.0.1 - - [21/Apr/2015 16:02:32] "POST /auth/facebook HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/sat/examples/server/python/app.py", line 188, in facebook
    user = User.query.filter_by(facebook=profile['id']).first()
KeyError: 'id'*

Following are the steps executed to run this application:
1. Created a App in facebook and set the URL to http://localhost:3000/
2. Got the APP ID from Fb and changed it in app.js
3. Got the facebook secret from FB and set the environment variable (i'm running ubuntu fyi)
4. Start the server using $node server.js  / $ python app.py (installed all necessary requirements)
5. Accessed the satellizer via URL http://localhost:3000

Am I doing anything wrong!!! Any help would be greatful

**Comment by mdtanrikulu** [comment]
Your facebook login configuration on back side is wrong probably. First check which version of Graph API you're using, I just update everything as 'v2.6' on backside and in satellizer library. Then edit "acces_token_url" from;
```
https://graph.facebook.com/v2.3/oauth/access_token
```

to
```
https://graph.facebook.com/oauth/access_token
```

By the way don't forget to add your facebook secret key in config.
If everything is right API will return user id and you wont get this error.
