### ISSUE TITLE
npm install doesn't work

### ISSUE THREAD

**Issue by paulstefanday** [sahat/satellizer#446]
I tried installing this using npm and I got this error:
I have gulp installed globally. 
```
Pauls-MacBook:tracker-front paulday$ sudo npm install satellizer --save-dev
Password:
npm WARN package.json @1.0.0 No repository field.
npm WARN package.json fs@0.0.2 fs is also the name of a node core module.
npm WARN package.json fs@0.0.2 No description
npm WARN package.json fs@0.0.2 No repository field.
/
> satellizer@0.11.1 postinstall /Users/paulday/Sites/tracker-front/node_modules/satellizer
> gulp copy && gulp php

[10:14:24] No gulpfile found
npm ERR! Darwin 14.1.1
npm ERR! argv "node" "/usr/local/bin/npm" "install" "satellizer" "--save-dev"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! satellizer@0.11.1 postinstall: `gulp copy && gulp php`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the satellizer@0.11.1 postinstall script 'gulp copy && gulp php'.
npm ERR! This is most likely a problem with the satellizer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp copy && gulp php
npm ERR! You can get their info via:
npm ERR!     npm owner ls satellizer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/paulday/Sites/tracker-front/npm-debug.log
```

Also here is the npm logs:
```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'satellizer',
1 verbose cli   '--save-dev' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 warn package.json @1.0.0 No repository field.
5 warn package.json fs@0.0.2 fs is also the name of a node core module.
6 warn package.json fs@0.0.2 No description
7 warn package.json fs@0.0.2 No repository field.
8 silly cache add args [ 'satellizer', null ]
9 verbose cache add spec satellizer
10 silly cache add parsed spec { raw: 'satellizer',
10 silly cache add   scope: null,
10 silly cache add   name: 'satellizer',
10 silly cache add   rawSpec: '',
10 silly cache add   spec: '*',
10 silly cache add   type: 'range' }
11 verbose addNamed satellizer@*
12 silly addNamed semver.valid null
13 silly addNamed semver.validRange *
14 silly addNameRange { name: 'satellizer', range: '*', hasData: false }
15 silly mapToRegistry name satellizer
16 silly mapToRegistry using default registry
17 silly mapToRegistry registry https://registry.npmjs.org/
18 silly mapToRegistry uri https://registry.npmjs.org/satellizer
19 verbose addNameRange registry:https://registry.npmjs.org/satellizer not in flight; fetching
20 verbose request uri https://registry.npmjs.org/satellizer
21 verbose request no auth needed
22 info attempt registry request try #1 at 10:14:22 AM
23 verbose request id 3fc159a339d74e71
24 verbose etag "UJRAEBT08POJLQ0YNDJNIPS"
25 http request GET https://registry.npmjs.org/satellizer
26 http 304 https://registry.npmjs.org/satellizer
27 silly get cb [ 304,
27 silly get   { date: 'Fri, 05 Jun 2015 00:14:22 GMT',
27 silly get     via: '1.1 varnish',
27 silly get     'cache-control': 'max-age=60',
27 silly get     etag: '"UJRAEBT08POJLQ0YNDJNIPS"',
27 silly get     age: '0',
27 silly get     connection: 'keep-alive',
27 silly get     'x-served-by': 'cache-syd1621-SYD',
27 silly get     'x-cache': 'MISS',
27 silly get     'x-cache-hits': '0',
27 silly get     'x-timer': 'S1433463262.657027,VS0,VE773',
27 silly get     vary: 'Accept' } ]
28 verbose etag https://registry.npmjs.org/satellizer from cache
29 verbose get saving satellizer to /Users/paulday/.npm/registry.npmjs.org/satellizer/.cache.json
30 silly addNameRange number 2 { name: 'satellizer', range: '*', hasData: true }
31 silly addNameRange versions [ 'satellizer',
31 silly addNameRange   [ '0.0.0',
31 silly addNameRange     '1.0.0',
31 silly addNameRange     '0.1.0',
31 silly addNameRange     '0.2.0',
31 silly addNameRange     '0.3.0',
31 silly addNameRange     '0.3.1',
31 silly addNameRange     '0.3.2',
31 silly addNameRange     '0.3.3',
31 silly addNameRange     '0.4.0',
31 silly addNameRange     '0.4.1',
31 silly addNameRange     '0.5.0',
31 silly addNameRange     '0.6.0',
31 silly addNameRange     '0.6.1',
31 silly addNameRange     '0.6.2',
31 silly addNameRange     '0.6.3',
31 silly addNameRange     '0.6.4',
31 silly addNameRange     '0.7.0',
31 silly addNameRange     '0.7.1',
31 silly addNameRange     '0.8.0',
31 silly addNameRange     '0.8.1',
31 silly addNameRange     '0.8.2',
31 silly addNameRange     '0.8.3',
31 silly addNameRange     '0.8.4',
31 silly addNameRange     '0.8.5',
31 silly addNameRange     '0.8.6',
31 silly addNameRange     '0.8.7',
31 silly addNameRange     '0.8.8',
31 silly addNameRange     '0.9.0',
31 silly addNameRange     '0.9.1',
31 silly addNameRange     '0.9.2',
31 silly addNameRange     '0.9.3',
31 silly addNameRange     '0.9.4',
31 silly addNameRange     '0.10.1',
31 silly addNameRange     '0.11.0',
31 silly addNameRange     '0.11.1' ] ]
32 verbose addNamed satellizer@0.11.1
33 silly addNamed semver.valid 0.11.1
34 silly addNamed semver.validRange 0.11.1
35 silly cache afterAdd satellizer@0.11.1
36 verbose afterAdd /Users/paulday/.npm/satellizer/0.11.1/package/package.json not in flight; writing
37 verbose afterAdd /Users/paulday/.npm/satellizer/0.11.1/package/package.json written
38 silly install resolved [ { name: 'satellizer',
38 silly install resolved     description: 'Token-based AngularJS Authentication',
38 silly install resolved     version: '0.11.1',
38 silly install resolved     scripts:
38 silly install resolved      { start: 'node ./examples/server/node/server.js',
38 silly install resolved        postinstall: 'gulp copy && gulp php',
38 silly install resolved        test: 'karma start' },
38 silly install resolved     main: 'satellizer.min.js',
38 silly install resolved     homepage: 'https://github.com/sahat/satellizer',
38 silly install resolved     bugs: { url: 'https://github.com/sahat/satellizer/issues' },
38 silly install resolved     repository:
38 silly install resolved      { type: 'git',
38 silly install resolved        url: 'git+https://github.com/sahat/satellizer.git' },
38 silly install resolved     author:
38 silly install resolved      { name: 'Sahat Yalkabov',
38 silly install resolved        email: 'sahat@me.com',
38 silly install resolved        url: 'http://sahatyalkabov.com' },
38 silly install resolved     devDependencies:
38 silly install resolved      { gulp: '^3.8.7',
38 silly install resolved        'gulp-complexity': '~0.3.0',
38 silly install resolved        'gulp-plumber': '^0.6.4',
38 silly install resolved        'gulp-rename': '^1.2.0',
38 silly install resolved        'gulp-uglify': '~1.0.0',
38 silly install resolved        'gulp-header': '~1.2.0',
38 silly install resolved        karma: '^0.12.21',
38 silly install resolved        'karma-coverage': '^0.2.6',
38 silly install resolved        'karma-jasmine': '^0.1.5',
38 silly install resolved        'karma-phantomjs-launcher': '^0.1.4' },
38 silly install resolved     license: 'MIT',
38 silly install resolved     tags:
38 silly install resolved      [ 'authentication',
38 silly install resolved        'login',
38 silly install resolved        'token',
38 silly install resolved        'jwt',
38 silly install resolved        'angularjs',
38 silly install resolved        'angular',
38 silly install resolved        'auth',
38 silly install resolved        'facebook',
38 silly install resolved        'google',
38 silly install resolved        'linkedin',
38 silly install resolved        'twitter',
38 silly install resolved        'foursquare',
38 silly install resolved        'github',
38 silly install resolved        'yahoo',
38 silly install resolved        'oauth',
38 silly install resolved        'oauth 1.0',
38 silly install resolved        'oauth 2.0',
38 silly install resolved        'oauth2',
38 silly install resolved        'oauth1',
38 silly install resolved        'sign-in',
38 silly install resolved        'social' ],
38 silly install resolved     gitHead: 'c4b956cc956c675f76936ec3ec1e56031f01feb6',
38 silly install resolved     _id: 'satellizer@0.11.1',
38 silly install resolved     _shasum: 'db22a7999bc4cc81f869d3a49f2d984e737e2428',
38 silly install resolved     _from: 'satellizer@*',
38 silly install resolved     _npmVersion: '2.10.1',
38 silly install resolved     _nodeVersion: '0.12.4',
38 silly install resolved     _npmUser: { name: 'sahat', email: 'sakhat@gmail.com' },
38 silly install resolved     dist:
38 silly install resolved      { shasum: 'db22a7999bc4cc81f869d3a49f2d984e737e2428',
38 silly install resolved        tarball: 'http://registry.npmjs.org/satellizer/-/satellizer-0.11.1.tgz' },
38 silly install resolved     maintainers: [ [Object] ],
38 silly install resolved     directories: {},
38 silly install resolved     _resolved: 'https://registry.npmjs.org/satellizer/-/satellizer-0.11.1.tgz',
38 silly install resolved     readme: 'ERROR: No README data found!' } ]
39 info install satellizer@0.11.1 into /Users/paulday/Sites/tracker-front
40 info installOne satellizer@0.11.1
41 verbose installOne of satellizer to /Users/paulday/Sites/tracker-front not in flight; installing
42 verbose lock using /Users/paulday/.npm/_locks/satellizer-49a4e569cfdbf9f2.lock for /Users/paulday/Sites/tracker-front/node_modules/satellizer
43 silly install write writing satellizer 0.11.1 to /Users/paulday/Sites/tracker-front/node_modules/satellizer
44 silly cache addNamed cb satellizer@0.11.1
45 verbose unbuild node_modules/satellizer
46 silly gentlyRm /Users/paulday/Sites/tracker-front/node_modules/satellizer is being purged from base /Users/paulday/Sites/tracker-front
47 verbose gentlyRm don't care about contents; nuking /Users/paulday/Sites/tracker-front/node_modules/satellizer
48 verbose tar unpack /Users/paulday/.npm/satellizer/0.11.1/package.tgz
49 verbose tar unpacking to /Users/paulday/Sites/tracker-front/node_modules/satellizer
50 silly gentlyRm /Users/paulday/Sites/tracker-front/node_modules/satellizer is being purged
51 verbose gentlyRm don't care about contents; nuking /Users/paulday/Sites/tracker-front/node_modules/satellizer
52 silly gunzTarPerm modes [ '755', '644' ]
53 silly gunzTarPerm extractEntry package.json
54 silly gunzTarPerm extractEntry .npmignore
55 silly gunzTarPerm extractEntry README.md
56 silly gunzTarPerm extractEntry LICENSE
57 silly gunzTarPerm extractEntry satellizer.min.js
58 silly gunzTarPerm extractEntry satellizer.js
59 silly gunzTarPerm extractEntry .jshintrc
60 info preinstall satellizer@0.11.1
61 silly install resolved []
```
62 verbose about to build /Users/paulday/Sites/tracker-front/node_modules/satellizer
63 info build /Users/paulday/Sites/tracker-front/node_modules/satellizer
64 verbose linkStuff [ false,
64 verbose linkStuff   false,
64 verbose linkStuff   false,
64 verbose linkStuff   '/Users/paulday/Sites/tracker-front/node_modules' ]
65 info linkStuff satellizer@0.11.1
66 verbose linkBins satellizer@0.11.1
67 verbose linkMans satellizer@0.11.1
68 verbose rebuildBundles satellizer@0.11.1
69 info install satellizer@0.11.1
70 info postinstall satellizer@0.11.1
71 verbose unsafe-perm in lifecycle false
72 info satellizer@0.11.1 Failed to exec postinstall script
73 verbose unlock done using /Users/paulday/.npm/_locks/satellizer-49a4e569cfdbf9f2.lock for /Users/paulday/Sites/tracker-front/node_modules/satellizer
74 verbose stack Error: satellizer@0.11.1 postinstall: `gulp copy && gulp php`
74 verbose stack Exit status 1
74 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
74 verbose stack     at EventEmitter.emit (events.js:110:17)
74 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
74 verbose stack     at ChildProcess.emit (events.js:110:17)
74 verbose stack     at maybeClose (child_process.js:1015:16)
74 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
75 verbose pkgid satellizer@0.11.1
76 verbose cwd /Users/paulday/Sites/tracker-front
77 error Darwin 14.1.1
78 error argv "node" "/usr/local/bin/npm" "install" "satellizer" "--save-dev"
79 error node v0.12.2
80 error npm  v2.7.4
81 error code ELIFECYCLE
82 error satellizer@0.11.1 postinstall: `gulp copy && gulp php`
82 error Exit status 1
83 error Failed at the satellizer@0.11.1 postinstall script 'gulp copy && gulp php'.
83 error This is most likely a problem with the satellizer package,
83 error not with npm itself.
83 error Tell the author that this fails on your system:
83 error     gulp copy && gulp php
83 error You can get their info via:
83 error     npm owner ls satellizer
83 error There is likely additional logging output above.
84 verbose exit [ 1, true ]
85 verbose unbuild node_modules/satellizer
86 info preuninstall satellizer@0.11.1
87 info uninstall satellizer@0.11.1
88 verbose unbuild rmStuff satellizer@0.11.1 from /Users/paulday/Sites/tracker-front/node_modules
89 info postuninstall satellizer@0.11.1
90 silly gentlyRm /Users/paulday/Sites/tracker-front/node_modules/satellizer is being purged from base /Users/paulday/Sites/tracker-front
91 verbose gentlyRm don't care about contents; nuking /Users/paulday/Sites/tracker-front/node_modules/satellizer
92 silly vacuum-fs purging /Users/paulday/Sites/tracker-front/node_modules/satellizer
93 silly vacuum-fs quitting because other entries in /Users/paulday/Sites/tracker-front/node_modules

**Comment by sahat** [comment]
Thanks for reporting this issue. I wanted to run those commands after `devDependencies` have been installed so you can try out server-side examples, but npm seems to run `gulp copy && gulp.php` in both cases:
1) when you simply want to download satellizer for your project.
2) when you clone satellizer repo and need to install dependencies to run server examples.

I will remove `postinstall` line from package.json in v0.11.2.

**Comment by sahat** [comment]
Fixed in 0.11.2.

**Comment by paulstefanday** [comment]
Thank you! Please publish latest to npm too. Thanks!

**Comment by sahat** [comment]
Woops, forgot to do that.
